// Gameplay module compatibility (T0104, D12).
//
// D12 lets rich C++ cross the engine/gameplay boundary — real types, templates,
// entt registries — instead of a C ABI with a generated binding layer. That is a
// large ergonomic win and it rests on one assumption: **the module was compiled
// against exactly this engine.**
//
// When the assumption holds, everything works. When it does not, nothing
// announces it. A module built against an engine whose class layout has since
// changed will load, resolve its symbols, and then read fields at the wrong
// offsets. The symptom is corrupted data or a crash somewhere unrelated,
// arbitrarily far from the cause, and the usual instinct — read the gameplay
// code — leads away from the actual problem.
//
// This is the guard that makes D12 safe, and it is deliberately not optional:
// every module gets stamped by `hp_add_gameplay_module()`, so one cannot be
// built without an id to check.
#pragma once

#include <hp/Api.hpp>

namespace hp {

/// The running engine's build id.
///
/// Derived from the public headers' contents plus the target triple, the build
/// type and every flag that changes the engine's symbol surface or type layout
/// (currently profiling). Regenerated by the build whenever any of those move,
/// so it cannot claim compatibility it does not have.
[[nodiscard]] HP_API const char* engineBuildId() noexcept;

/// The symbol every gameplay module exports carrying the id it was built with.
///
/// Named here rather than in the loader so that the engine and whatever loads
/// modules cannot disagree about it. The loader resolves this, then hands the
/// value to `checkModuleBuildId` — which is what keeps the check independent of
/// *how* a module was loaded (`dlopen`, `LoadLibrary`, a test harness, or
/// whatever T0048 ends up building).
inline constexpr const char* kModuleBuildIdSymbol = "hp_module_build_id";

/// Signature of that symbol.
using ModuleBuildIdFn = const char* (*)();

/// Outcome of a compatibility check.
///
/// `message` is populated on failure and is meant to be shown to a developer
/// verbatim: it names the module, both ids, and what to rebuild. A refusal that
/// does not say what to do is only marginally better than the corruption it
/// prevents.
struct ModuleCompatibility {
    bool compatible = false;
    const char* engine_id = "";
    const char* module_id = "";
};

/// Compare a module's stamped id against the running engine's.
///
/// Deliberately **equal-or-refuse**. There is no version negotiation, no
/// compatibility window and no "minor versions are compatible" — D12's lockstep
/// means there is exactly one right answer at any moment, and every mechanism
/// for expressing a range is a mechanism that has to be maintained and reasoned
/// about. If lockstep is ever abandoned, this design is the wrong starting point
/// anyway.
///
/// @param module_id the value of the module's `hp_module_build_id` symbol. May
///        be null, which is what a module built without the stamp looks like —
///        that is a refusal, not a pass, because an unstamped module is the case
///        with no evidence either way rather than the case that is probably fine.
/// @returns whether the module may be loaded, plus both ids for reporting.
[[nodiscard]] HP_API ModuleCompatibility checkModuleBuildId(const char* module_id) noexcept;

/// Build the developer-facing refusal text for a failed check.
///
/// Separate from the check so a caller can decide where it goes — the editor
/// wants it in a panel, the runtime in a log, a test in an assertion message.
/// @param module_name shown to the developer so the message names which module
///        was refused; may be null, rendered as `<module>`.
/// @param result the outcome from `checkModuleBuildId`.
/// @returns a pointer to a thread-local buffer, valid until the next call on the
///          same thread. Not owned by the caller and not freed.
[[nodiscard]] HP_API const char* describeIncompatibility(const char* module_name,
                                                         ModuleCompatibility result) noexcept;

} // namespace hp
