#!/usr/bin/env python3
"""Generate the markdown API reference from engine/include/hp/ (T0118).

The consumer is a **coding agent**, not a human browsing a website, and that
changes almost every decision here:

  * **Stale output is a correctness bug, not an annoyance.** A human reading
    outdated docs is mildly misled; an agent writes code calling a function that
    does not exist, confidently. So this is generated by the build rather than
    maintained by hand, and CI fails on a dirty tree afterwards.
  * **Completeness beats polish.** A missing symbol is worse than a tersely
    documented one, because absence invites the agent to invent an API. Every
    public declaration appears, documented or not, and undocumented ones are
    marked so the gap is visible rather than silent.
  * **The prose is the point.** This project's comments explain *why* -- why a
    LogCategory is a handle, why sinks are non-owning. That is exactly what
    stops an agent misusing an API, so doc comments are reproduced in full
    rather than truncated to a summary line.

Tooling choice (118.1): **libclang**. `clang-doc` is not in the pinned toolchain
(checked). Doxygen is on this host but would be an unpinned host dependency --
the very thing D5 exists to prevent -- and its markdown output is shaped for
human browsing rather than for an agent. libclang gives exact signatures, and
Python is already required by the build (DiligentCore pip-installs jinja2 during
configure), so this adds a dependency of a kind the project already carries.

Diagnostics rule, and it matters: the host's libclang is a different LLVM
version from the one zig bundles, so parsing zig's libc++ headers produces
errors that are pure version-mismatch noise. **Errors originating in our own
headers are fatal; errors inside standard-library headers are reported and
tolerated.** Verified: extraction from a header with 13 libc++ errors and zero
own-header errors is complete and correct.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys

try:
    import clang.cindex as cx
except ImportError:
    sys.exit(
        "error: python libclang is required.\n"
        "  pip install libclang\n"
        "This is a host tool -- it never cross-compiles and is not part of a target build."
    )

# Declarations worth documenting. Deliberately excludes things an agent cannot
# call: field declarations are covered by their parent struct's signature block,
# and parameters appear in the signature itself.
DOCUMENTED_KINDS = {
    cx.CursorKind.FUNCTION_DECL,
    cx.CursorKind.CXX_METHOD,
    cx.CursorKind.CONSTRUCTOR,
    cx.CursorKind.CLASS_DECL,
    cx.CursorKind.STRUCT_DECL,
    cx.CursorKind.ENUM_DECL,
    cx.CursorKind.CLASS_TEMPLATE,
    cx.CursorKind.FUNCTION_TEMPLATE,
    cx.CursorKind.TYPEDEF_DECL,
    cx.CursorKind.TYPE_ALIAS_DECL,
}

CALLABLE_KINDS = {
    cx.CursorKind.FUNCTION_DECL,
    cx.CursorKind.CXX_METHOD,
    cx.CursorKind.CONSTRUCTOR,
    cx.CursorKind.FUNCTION_TEMPLATE,
}

CONTAINER_KINDS = {
    cx.CursorKind.CLASS_DECL,
    cx.CursorKind.STRUCT_DECL,
    cx.CursorKind.CLASS_TEMPLATE,
}


def zig_include_paths(zig: pathlib.Path) -> list[str]:
    """The include search path zig itself uses.

    Asked of the toolchain rather than hardcoded, so the reference describes the
    API as the real build sees it and does not drift when zig is bumped.
    """
    try:
        out = subprocess.run(
            [str(zig), "c++", "-E", "-x", "c++", "-", "-v"],
            input="",
            capture_output=True,
            text=True,
            timeout=60,
        ).stderr
    except (OSError, subprocess.SubprocessError):
        return []
    paths: list[str] = []
    collecting = False
    for line in out.splitlines():
        if "#include <...> search starts here" in line:
            collecting = True
            continue
        if "End of search list" in line:
            break
        if collecting:
            candidate = line.strip()
            if candidate:
                paths.append(candidate)
    return paths


def clean_comment(raw: str | None) -> str:
    """Strip comment markers, keeping the prose and any @tags intact."""
    if not raw:
        return ""
    lines: list[str] = []
    for line in raw.splitlines():
        line = line.strip()
        line = re.sub(r"^/\*\*+<?", "", line)
        line = re.sub(r"^///+<?", "", line)
        line = re.sub(r"^//+", "", line)
        line = re.sub(r"\*/$", "", line)
        line = re.sub(r"^\*+ ?", "", line)
        lines.append(line.rstrip())
    while lines and not lines[0]:
        lines.pop(0)
    while lines and not lines[-1]:
        lines.pop()
    return "\n".join(lines)


def parameters_of(cursor) -> list:
    """Parameter cursors, including for function templates.

    `get_arguments()` returns **nothing** for a `FUNCTION_TEMPLATE` -- measured,
    not assumed -- while the PARM_DECL children are present and correct. Relying
    on it alone made every templated function look like it took no arguments,
    which had two consequences and both are the failure mode this tool exists to
    prevent:

      * signatures rendered as `property()` for something taking a `const char*`,
        which is documentation that is confidently wrong
      * `missing-param` could never fire for a template, while `stale-param`
        fired for every correctly documented one -- and stale-param is the one
        defect that is never baselinable

    Found when <hp/Reflect.hpp> arrived (T0053), the first public header with a
    substantially templated surface.
    """
    args = list(cursor.get_arguments())
    if args:
        return args
    return [c for c in cursor.get_children() if c.kind == cx.CursorKind.PARM_DECL]


def signature(cursor) -> str:
    """A signature an agent can copy, rather than a name."""
    if cursor.kind in CONTAINER_KINDS:
        keyword = "struct" if cursor.kind == cx.CursorKind.STRUCT_DECL else "class"
        return f"{keyword} {cursor.spelling}"
    if cursor.kind == cx.CursorKind.ENUM_DECL:
        return f"enum class {cursor.spelling}"
    if cursor.kind in (cx.CursorKind.TYPEDEF_DECL, cx.CursorKind.TYPE_ALIAS_DECL):
        return f"using {cursor.spelling} = {cursor.underlying_typedef_type.spelling}"

    result = cursor.result_type.spelling
    params = ", ".join(
        f"{p.type.spelling} {p.spelling}".strip() for p in parameters_of(cursor)
    )
    text = f"{cursor.spelling}({params})"
    if result and cursor.kind != cx.CursorKind.CONSTRUCTOR:
        text = f"{result} {text}"
    if cursor.is_static_method():
        text = f"static {text}"
    if cursor.is_const_method():
        text += " const"
    return text


def is_public(cursor) -> bool:
    return cursor.access_specifier in (
        cx.AccessSpecifier.PUBLIC,
        cx.AccessSpecifier.INVALID,  # namespace scope
    )


def collect(tu, header: pathlib.Path):
    """Public declarations that physically live in `header`."""
    found: list[dict] = []

    def visit(cursor, owner: str | None):
        for child in cursor.get_children():
            loc = child.location.file
            if loc is None or pathlib.Path(loc.name) != header:
                continue
            if child.kind in DOCUMENTED_KINDS and is_public(child):
                entry = {
                    "kind": child.kind,
                    "name": child.spelling,
                    "signature": signature(child),
                    "doc": clean_comment(child.raw_comment),
                    "owner": owner,
                    "enumerators": [],
                    "params": [p.spelling for p in parameters_of(child)]
                    if child.kind in CALLABLE_KINDS
                    else [],
                    "returns": child.result_type.spelling
                    if child.kind in CALLABLE_KINDS
                    else "",
                    "is_callable": child.kind in CALLABLE_KINDS,
                    "line": child.location.line,
                }
                if child.kind == cx.CursorKind.ENUM_DECL:
                    entry["enumerators"] = [
                        (c.spelling, c.enum_value)
                        for c in child.get_children()
                        if c.kind == cx.CursorKind.ENUM_CONSTANT_DECL
                    ]
                found.append(entry)
                if child.kind in CONTAINER_KINDS:
                    visit(child, child.spelling)
                    continue
            visit(child, owner)

    visit(tu.cursor, None)
    return found


def render_header(header: pathlib.Path, entries: list[dict], preamble: str) -> str:
    out: list[str] = []
    out.append(f"# `<hp/{header.name}>`")
    out.append("")
    out.append(f"*Generated from `engine/include/hp/{header.name}` — do not edit.*")
    out.append("")
    if preamble:
        out.append(preamble)
        out.append("")
    out.append(f"```cpp\n#include <hp/{header.name}>\n```")
    out.append("")

    undocumented = [e for e in entries if not e["doc"]]
    out.append(
        f"{len(entries)} public declaration(s), "
        f"{len(entries) - len(undocumented)} documented."
    )
    out.append("")

    for entry in entries:
        title = entry["name"]
        if entry["owner"]:
            title = f"{entry['owner']}::{entry['name']}"
        out.append(f"## `{title}`")
        out.append("")
        out.append(f"```cpp\n{entry['signature']}\n```")
        out.append("")
        if entry["enumerators"]:
            out.append("| Enumerator | Value |")
            out.append("|---|---|")
            for name, value in entry["enumerators"]:
                out.append(f"| `{name}` | {value} |")
            out.append("")
        if entry["doc"]:
            out.append(entry["doc"])
        else:
            # Stated rather than omitted: an agent must be able to tell "no
            # documentation" from "not part of the API".
            out.append("*No documentation comment.*")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_index(per_header: dict[str, list[dict]], rules: str) -> str:
    out: list[str] = []
    out.append("# HollowPoint engine API")
    out.append("")
    out.append("*Generated by `zig build docs` from `engine/include/hp/` — do not edit.*")
    out.append("")
    out.append(
        "This is the complete public surface of the engine library. Gameplay code "
        "is C++ compiled against these headers in lockstep with the engine (D12), "
        "so this is the API a game is written against."
    )
    out.append("")
    out.append(rules)
    out.append("")
    out.append("## Headers")
    out.append("")
    out.append("| Header | Declarations | Documented |")
    out.append("|---|---|---|")
    for name in sorted(per_header):
        entries = per_header[name]
        documented = sum(1 for e in entries if e["doc"])
        out.append(f"| [`<hp/{name}>`]({pathlib.Path(name).stem}.md) | {len(entries)} | {documented} |")
    out.append("")
    total = sum(len(v) for v in per_header.values())
    documented = sum(1 for v in per_header.values() for e in v if e["doc"])
    out.append(f"**{total} public declarations across {len(per_header)} headers, "
               f"{documented} documented.**")
    out.append("")
    out.append("## Every symbol")
    out.append("")
    out.append("| Symbol | Header |")
    out.append("|---|---|")
    for name in sorted(per_header):
        for entry in per_header[name]:
            symbol = f"{entry['owner']}::{entry['name']}" if entry["owner"] else entry["name"]
            out.append(f"| `{symbol}` | [`{name}`]({pathlib.Path(name).stem}.md) |")
    return "\n".join(out).rstrip() + "\n"


# Cross-cutting constraints (118.4). These live next to the API rather than only
# in the conventions document, because an agent reads what it is given and a
# separate file it was never pointed at may as well not exist.
RULES = """## Rules that apply to all of this

These are not style preferences. Violating one produces code that compiles and
then misbehaves at run time, so they are repeated here rather than left in a
document an agent may not read.

- **Do not throw across the engine boundary.** Engine code does not throw;
  failures are returned. Diligent's exceptions are converted at the call site.
- **Memory is freed by the side that allocated it.** Each shared library carries
  its own statically linked libc++, so an allocation crossing the gameplay-module
  boundary must return to its owner to be released. Prefer handles.
- **Never persist or compare `entt::type_index` across the boundary.** It is a
  per-module runtime number: the same type gets different values in the engine
  and in a gameplay module. Use `entt::type_hash`, or a stable name.
- **`HP_ASSERT` is compiled out in release** and must have no side effects.
  `HP_CHECK` survives; use it where a violation would corrupt data.
- **Profiling and logging macros do not evaluate their arguments when disabled.**
  A variable used only inside one will look unused.
- Types crossing the boundary need default visibility for RTTI to work.

Full reasoning: `claude_documentation/documentation/06-engine-conventions.md`."""


TAG_RE = re.compile(r"^\s*[@\\](param|returns?|throws?)\b\s*(\S+)?", re.M)


def check_entry(header: str, entry: dict) -> list[str]:
    """Documentation defects in one declaration, as human-readable strings.

    Three kinds, in increasing order of how badly they mislead:

      missing-doc    no comment at all. An agent sees the signature and guesses
                     the semantics.
      missing-param  a parameter with no @param. The agent guesses that one.
      stale-param    an @param naming a parameter that does not exist. **This is
                     the worst of the three** and the reason this check exists:
                     it is documentation that is confidently wrong, which is
                     strictly more dangerous than documentation that is absent.
                     It happens whenever someone renames a parameter and does
                     not update the comment, which nothing else would catch.
    """
    # Identity deliberately excludes the line number. Keying a baseline on
    # `file:line` means any edit above a defect invalidates its entry, so the
    # ratchet reports the whole file as new the first time someone adds a
    # comment near the top -- which is exactly what happened, 72 spurious
    # "new" defects from one unrelated edit. The line is reported for
    # navigation and is not part of the key.
    where = f"{header} {entry['owner'] + '::' if entry['owner'] else ''}{entry['name']}"
    problems: list[str] = []
    doc = entry["doc"]

    if not doc:
        return [f"{where}: missing-doc"]

    if not entry["is_callable"]:
        return problems

    tagged = {m.group(2) for m in TAG_RE.finditer(doc) if m.group(1) == "param" and m.group(2)}
    declared = {p for p in entry["params"] if p}

    for name in sorted(declared - tagged):
        problems.append(f"{where}: missing-param '{name}'")
    for name in sorted(tagged - declared):
        problems.append(f"{where}: stale-param '{name}' (no such parameter)")

    returns_something = entry["returns"] not in ("", "void")
    documents_return = any(
        m.group(1).startswith("return") for m in TAG_RE.finditer(doc)
    )
    if returns_something and not documents_return and entry["params"]:
        # Only demanded where the function also takes parameters: a bare
        # `int frame() const` whose prose already says what it returns does not
        # need a tag, and demanding one produces noise nobody reads.
        problems.append(f"{where}: missing-returns ({entry['returns']})")

    return problems


def load_baseline(path: pathlib.Path) -> set[str]:
    """Known defects, so the check can be strict about *new* ones today.

    A ratchet, not an exemption list. Turning the check on strictly at 39-of-87
    documented would fail every build until someone wrote 48 comments in one
    sitting, which means the check would simply be disabled instead. With a
    baseline, new public API must be documented from the first commit and the
    existing gap can only shrink -- removing a line is a one-line diff.

    Deliberately a list of specific defects rather than a count: a count lets
    someone fix one and break another and stay green.
    """
    if not path.exists():
        return set()
    return {
        line.strip()
        for line in path.read_text().splitlines()
        if line.strip() and not line.startswith("#")
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--include", required=True, help="engine/include")
    parser.add_argument("--out", required=True, help="output directory")
    parser.add_argument("--zig", default="", help="zig executable, for include paths")
    parser.add_argument("--isystem", action="append", default=[],
                        help="extra system include directory, repeatable. Public headers may "
                             "include vendored third-party headers (entt, for one); without "
                             "these libclang cannot parse them and the run aborts rather than "
                             "emitting an incomplete reference.")
    parser.add_argument("--define", action="append", default=[],
                        help="preprocessor definition, repeatable, e.g. PLATFORM_LINUX=1. "
                             "Diligent's headers -- which <hp/Math.hpp> includes -- are a "
                             "hard #error without a platform macro, so parsing them needs "
                             "the same define the build passes.")
    parser.add_argument("--check", action="store_true",
                        help="fail on documentation defects not present in the baseline")
    parser.add_argument("--baseline", default="tools/api_docs_baseline.txt",
                        help="known defects, which may shrink but never grow")
    parser.add_argument("--write-baseline", action="store_true",
                        help="record current defects as the baseline (use deliberately)")
    parser.add_argument("--stamp", default="",
                        help="write a stamp file here after a successful run (T0123). "
                             "This exists for the build graph, not for humans: zig's Run "
                             "step only caches a command it believes produces output, and "
                             "the real output lands in the source tree where zig cannot "
                             "model it. The stamp is that declared output.")
    args = parser.parse_args()

    include_root = pathlib.Path(args.include).resolve()
    out_dir = pathlib.Path(args.out).resolve()
    headers = sorted((include_root / "hp").glob("*.hpp"))
    if not headers:
        print(f"error: no headers under {include_root}/hp", file=sys.stderr)
        return 1

    flags = [
        "-std=c++20",
        "-x",
        "c++",
        f"-I{include_root}",
        # Silences a libc++ configuration assertion; harmless for parsing.
        "-D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_NONE",
    ]
    if args.zig:
        flags += [f"-isystem{p}" for p in zig_include_paths(pathlib.Path(args.zig))]
    flags += [f"-isystem{d}" for d in args.isystem]
    flags += [f"-D{d}" for d in args.define]

    index = cx.Index.create()
    per_header: dict[str, list[dict]] = {}
    fatal = 0

    for header in headers:
        tu = index.parse(str(header), args=flags)
        errors = [d for d in tu.diagnostics if d.severity >= cx.Diagnostic.Error]
        # The rule that makes this trustworthy: noise from a libclang/libc++
        # version mismatch is tolerated, an error in our own header is not.
        ours = [
            d for d in errors
            if d.location.file and pathlib.Path(d.location.file.name).is_relative_to(include_root)
        ]
        for diag in ours:
            print(f"error: {diag.location.file}:{diag.location.line}: {diag.spelling}",
                  file=sys.stderr)
        fatal += len(ours)
        per_header[header.name] = collect(tu, header)

    if fatal:
        print(f"error: {fatal} error(s) in public headers -- refusing to write a "
              f"reference that may be incomplete", file=sys.stderr)
        return 1

    # --- documentation checks ------------------------------------------------
    defects: list[str] = []
    for header in headers:
        for entry in per_header[header.name]:
            defects.extend(check_entry(header.name, entry))

    baseline_path = pathlib.Path(args.baseline)
    if args.write_baseline:
        baseline_path.write_text(
            "# Known API documentation defects (T0118).\n"
            "#\n"
            "# A ratchet: this list may shrink, never grow. `zig build docs -Dcheck`\n"
            "# fails on any defect not listed here, so new public API must be\n"
            "# documented from its first commit while the existing gap is paid down\n"
            "# over time.\n"
            "#\n"
            "# Regenerate deliberately with --write-baseline; do not do it to make a\n"
            "# failure go away.\n"
            + "\n".join(sorted(defects)) + "\n"
        )
        print(f"api docs: baseline written with {len(defects)} known defect(s)")

    if args.check:
        known = load_baseline(baseline_path)
        # stale-param is never baselinable. The others are gaps; this one is a
        # statement that is *wrong*, and a ratchet that tolerates wrong
        # documentation defeats the purpose of having the check at all.
        new_defects = [d for d in defects if d not in known or "stale-param" in d]
        fixed = len(known) - (len(defects) - len(new_defects))
        for defect in new_defects:
            print(f"error: {defect}", file=sys.stderr)
        # Line numbers are printed alongside but never keyed on -- see check_entry.
        if new_defects:
            print(
                f"error: {len(new_defects)} new API documentation defect(s).\n"
                f"  Public API must be documented as it is written. Add the missing\n"
                f"  comment or @param tag -- do not add it to the baseline.",
                file=sys.stderr,
            )
            return 1
        if fixed > 0:
            print(f"api docs: {fixed} baselined defect(s) now fixed -- "
                  f"regenerate the baseline with --write-baseline to lock that in")
        print(f"api docs: check passed ({len(defects)} known defect(s) remaining)")

    out_dir.mkdir(parents=True, exist_ok=True)
    for header in headers:
        text = render_header(header, per_header[header.name], "")
        (out_dir / f"{header.stem}.md").write_text(text)
    (out_dir / "index.md").write_text(render_index(per_header, RULES))

    total = sum(len(v) for v in per_header.values())
    documented = sum(1 for v in per_header.values() for e in v if e["doc"])
    print(f"api docs: {total} declarations across {len(headers)} headers "
          f"({documented} documented) -> {out_dir}")

    # Written last, so it exists only if everything above succeeded. A stamp
    # left behind by a failed run would let the build cache a failure.
    if args.stamp:
        stamp = pathlib.Path(args.stamp)
        stamp.parent.mkdir(parents=True, exist_ok=True)
        stamp.write_text(
            f"{total} declarations across {len(headers)} headers, {documented} documented\n"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
