#!/usr/bin/env python3
"""Generate the markdown API reference from engine/include/hp/ (T0118).

The consumer is a **coding agent**, not a human browsing a website, and that
changes almost every decision here:

  * **Stale output is a correctness bug, not an annoyance.** A human reading
    outdated docs is mildly misled; an agent writes code calling a function that
    does not exist, confidently. So this is generated by the build rather than
    maintained by hand, and CI fails on a dirty tree afterwards.
  * **Completeness beats polish.** A missing symbol is worse than a tersely
    documented one, because absence invites the agent to invent an API. Every
    public declaration appears, documented or not, and undocumented ones are
    marked so the gap is visible rather than silent.
  * **The prose is the point.** This project's comments explain *why* -- why a
    LogCategory is a handle, why sinks are non-owning. That is exactly what
    stops an agent misusing an API, so doc comments are reproduced in full
    rather than truncated to a summary line.

Tooling choice (118.1): **libclang**. `clang-doc` is not in the pinned toolchain
(checked). Doxygen is on this host but would be an unpinned host dependency --
the very thing D5 exists to prevent -- and its markdown output is shaped for
human browsing rather than for an agent. libclang gives exact signatures, and
Python is already required by the build (DiligentCore pip-installs jinja2 during
configure), so this adds a dependency of a kind the project already carries.

Diagnostics rule, and it matters: the host's libclang is a different LLVM
version from the one zig bundles, so parsing zig's libc++ headers produces
errors that are pure version-mismatch noise. **Errors originating in our own
headers are fatal; errors inside standard-library headers are reported and
tolerated.** Verified: extraction from a header with 13 libc++ errors and zero
own-header errors is complete and correct.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys

try:
    import clang.cindex as cx
except ImportError:
    sys.exit(
        "error: python libclang is required.\n"
        "  pip install libclang\n"
        "This is a host tool -- it never cross-compiles and is not part of a target build."
    )

# Declarations worth documenting. Deliberately excludes things an agent cannot
# call: field declarations are covered by their parent struct's signature block,
# and parameters appear in the signature itself.
DOCUMENTED_KINDS = {
    cx.CursorKind.FUNCTION_DECL,
    cx.CursorKind.CXX_METHOD,
    cx.CursorKind.CONSTRUCTOR,
    cx.CursorKind.CLASS_DECL,
    cx.CursorKind.STRUCT_DECL,
    cx.CursorKind.ENUM_DECL,
    cx.CursorKind.CLASS_TEMPLATE,
    cx.CursorKind.FUNCTION_TEMPLATE,
    cx.CursorKind.TYPEDEF_DECL,
    cx.CursorKind.TYPE_ALIAS_DECL,
}

CONTAINER_KINDS = {
    cx.CursorKind.CLASS_DECL,
    cx.CursorKind.STRUCT_DECL,
    cx.CursorKind.CLASS_TEMPLATE,
}


def zig_include_paths(zig: pathlib.Path) -> list[str]:
    """The include search path zig itself uses.

    Asked of the toolchain rather than hardcoded, so the reference describes the
    API as the real build sees it and does not drift when zig is bumped.
    """
    try:
        out = subprocess.run(
            [str(zig), "c++", "-E", "-x", "c++", "-", "-v"],
            input="",
            capture_output=True,
            text=True,
            timeout=60,
        ).stderr
    except (OSError, subprocess.SubprocessError):
        return []
    paths: list[str] = []
    collecting = False
    for line in out.splitlines():
        if "#include <...> search starts here" in line:
            collecting = True
            continue
        if "End of search list" in line:
            break
        if collecting:
            candidate = line.strip()
            if candidate:
                paths.append(candidate)
    return paths


def clean_comment(raw: str | None) -> str:
    """Strip comment markers, keeping the prose and any @tags intact."""
    if not raw:
        return ""
    lines: list[str] = []
    for line in raw.splitlines():
        line = line.strip()
        line = re.sub(r"^/\*\*+<?", "", line)
        line = re.sub(r"^///+<?", "", line)
        line = re.sub(r"^//+", "", line)
        line = re.sub(r"\*/$", "", line)
        line = re.sub(r"^\*+ ?", "", line)
        lines.append(line.rstrip())
    while lines and not lines[0]:
        lines.pop(0)
    while lines and not lines[-1]:
        lines.pop()
    return "\n".join(lines)


def signature(cursor) -> str:
    """A signature an agent can copy, rather than a name."""
    if cursor.kind in CONTAINER_KINDS:
        keyword = "struct" if cursor.kind == cx.CursorKind.STRUCT_DECL else "class"
        return f"{keyword} {cursor.spelling}"
    if cursor.kind == cx.CursorKind.ENUM_DECL:
        return f"enum class {cursor.spelling}"
    if cursor.kind in (cx.CursorKind.TYPEDEF_DECL, cx.CursorKind.TYPE_ALIAS_DECL):
        return f"using {cursor.spelling} = {cursor.underlying_typedef_type.spelling}"

    result = cursor.result_type.spelling
    params = ", ".join(
        f"{p.type.spelling} {p.spelling}".strip() for p in cursor.get_arguments()
    )
    text = f"{cursor.spelling}({params})"
    if result and cursor.kind != cx.CursorKind.CONSTRUCTOR:
        text = f"{result} {text}"
    if cursor.is_static_method():
        text = f"static {text}"
    if cursor.is_const_method():
        text += " const"
    return text


def is_public(cursor) -> bool:
    return cursor.access_specifier in (
        cx.AccessSpecifier.PUBLIC,
        cx.AccessSpecifier.INVALID,  # namespace scope
    )


def collect(tu, header: pathlib.Path):
    """Public declarations that physically live in `header`."""
    found: list[dict] = []

    def visit(cursor, owner: str | None):
        for child in cursor.get_children():
            loc = child.location.file
            if loc is None or pathlib.Path(loc.name) != header:
                continue
            if child.kind in DOCUMENTED_KINDS and is_public(child):
                entry = {
                    "kind": child.kind,
                    "name": child.spelling,
                    "signature": signature(child),
                    "doc": clean_comment(child.raw_comment),
                    "owner": owner,
                    "enumerators": [],
                }
                if child.kind == cx.CursorKind.ENUM_DECL:
                    entry["enumerators"] = [
                        (c.spelling, c.enum_value)
                        for c in child.get_children()
                        if c.kind == cx.CursorKind.ENUM_CONSTANT_DECL
                    ]
                found.append(entry)
                if child.kind in CONTAINER_KINDS:
                    visit(child, child.spelling)
                    continue
            visit(child, owner)

    visit(tu.cursor, None)
    return found


def render_header(header: pathlib.Path, entries: list[dict], preamble: str) -> str:
    out: list[str] = []
    out.append(f"# `<hp/{header.name}>`")
    out.append("")
    out.append(f"*Generated from `engine/include/hp/{header.name}` — do not edit.*")
    out.append("")
    if preamble:
        out.append(preamble)
        out.append("")
    out.append(f"```cpp\n#include <hp/{header.name}>\n```")
    out.append("")

    undocumented = [e for e in entries if not e["doc"]]
    out.append(
        f"{len(entries)} public declaration(s), "
        f"{len(entries) - len(undocumented)} documented."
    )
    out.append("")

    for entry in entries:
        title = entry["name"]
        if entry["owner"]:
            title = f"{entry['owner']}::{entry['name']}"
        out.append(f"## `{title}`")
        out.append("")
        out.append(f"```cpp\n{entry['signature']}\n```")
        out.append("")
        if entry["enumerators"]:
            out.append("| Enumerator | Value |")
            out.append("|---|---|")
            for name, value in entry["enumerators"]:
                out.append(f"| `{name}` | {value} |")
            out.append("")
        if entry["doc"]:
            out.append(entry["doc"])
        else:
            # Stated rather than omitted: an agent must be able to tell "no
            # documentation" from "not part of the API".
            out.append("*No documentation comment.*")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_index(per_header: dict[str, list[dict]], rules: str) -> str:
    out: list[str] = []
    out.append("# HollowPoint engine API")
    out.append("")
    out.append("*Generated by `zig build docs` from `engine/include/hp/` — do not edit.*")
    out.append("")
    out.append(
        "This is the complete public surface of the engine library. Gameplay code "
        "is C++ compiled against these headers in lockstep with the engine (D12), "
        "so this is the API a game is written against."
    )
    out.append("")
    out.append(rules)
    out.append("")
    out.append("## Headers")
    out.append("")
    out.append("| Header | Declarations | Documented |")
    out.append("|---|---|---|")
    for name in sorted(per_header):
        entries = per_header[name]
        documented = sum(1 for e in entries if e["doc"])
        out.append(f"| [`<hp/{name}>`]({pathlib.Path(name).stem}.md) | {len(entries)} | {documented} |")
    out.append("")
    total = sum(len(v) for v in per_header.values())
    documented = sum(1 for v in per_header.values() for e in v if e["doc"])
    out.append(f"**{total} public declarations across {len(per_header)} headers, "
               f"{documented} documented.**")
    out.append("")
    out.append("## Every symbol")
    out.append("")
    out.append("| Symbol | Header |")
    out.append("|---|---|")
    for name in sorted(per_header):
        for entry in per_header[name]:
            symbol = f"{entry['owner']}::{entry['name']}" if entry["owner"] else entry["name"]
            out.append(f"| `{symbol}` | [`{name}`]({pathlib.Path(name).stem}.md) |")
    return "\n".join(out).rstrip() + "\n"


# Cross-cutting constraints (118.4). These live next to the API rather than only
# in the conventions document, because an agent reads what it is given and a
# separate file it was never pointed at may as well not exist.
RULES = """## Rules that apply to all of this

These are not style preferences. Violating one produces code that compiles and
then misbehaves at run time, so they are repeated here rather than left in a
document an agent may not read.

- **Do not throw across the engine boundary.** Engine code does not throw;
  failures are returned. Diligent's exceptions are converted at the call site.
- **Memory is freed by the side that allocated it.** Each shared library carries
  its own statically linked libc++, so an allocation crossing the gameplay-module
  boundary must return to its owner to be released. Prefer handles.
- **Never persist or compare `entt::type_index` across the boundary.** It is a
  per-module runtime number: the same type gets different values in the engine
  and in a gameplay module. Use `entt::type_hash`, or a stable name.
- **`HP_ASSERT` is compiled out in release** and must have no side effects.
  `HP_CHECK` survives; use it where a violation would corrupt data.
- **Profiling and logging macros do not evaluate their arguments when disabled.**
  A variable used only inside one will look unused.
- Types crossing the boundary need default visibility for RTTI to work.

Full reasoning: `claude_documentation/documentation/06-engine-conventions.md`."""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--include", required=True, help="engine/include")
    parser.add_argument("--out", required=True, help="output directory")
    parser.add_argument("--zig", default="", help="zig executable, for include paths")
    args = parser.parse_args()

    include_root = pathlib.Path(args.include).resolve()
    out_dir = pathlib.Path(args.out).resolve()
    headers = sorted((include_root / "hp").glob("*.hpp"))
    if not headers:
        print(f"error: no headers under {include_root}/hp", file=sys.stderr)
        return 1

    flags = [
        "-std=c++20",
        "-x",
        "c++",
        f"-I{include_root}",
        # Silences a libc++ configuration assertion; harmless for parsing.
        "-D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_NONE",
    ]
    if args.zig:
        flags += [f"-isystem{p}" for p in zig_include_paths(pathlib.Path(args.zig))]

    index = cx.Index.create()
    per_header: dict[str, list[dict]] = {}
    fatal = 0

    for header in headers:
        tu = index.parse(str(header), args=flags)
        errors = [d for d in tu.diagnostics if d.severity >= cx.Diagnostic.Error]
        # The rule that makes this trustworthy: noise from a libclang/libc++
        # version mismatch is tolerated, an error in our own header is not.
        ours = [
            d for d in errors
            if d.location.file and pathlib.Path(d.location.file.name).is_relative_to(include_root)
        ]
        for diag in ours:
            print(f"error: {diag.location.file}:{diag.location.line}: {diag.spelling}",
                  file=sys.stderr)
        fatal += len(ours)
        per_header[header.name] = collect(tu, header)

    if fatal:
        print(f"error: {fatal} error(s) in public headers -- refusing to write a "
              f"reference that may be incomplete", file=sys.stderr)
        return 1

    out_dir.mkdir(parents=True, exist_ok=True)
    for header in headers:
        text = render_header(header, per_header[header.name], "")
        (out_dir / f"{header.stem}.md").write_text(text)
    (out_dir / "index.md").write_text(render_index(per_header, RULES))

    total = sum(len(v) for v in per_header.values())
    documented = sum(1 for v in per_header.values() for e in v if e["doc"])
    print(f"api docs: {total} declarations across {len(headers)} headers "
          f"({documented} documented) -> {out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
