# Generates the engine build id (T0104). Run with `cmake -P`, from a custom
# command that DEPENDS on the public headers.
#
# Run at BUILD time, not configure time, and that is the whole point. A hash
# computed during configure goes stale the moment a header changes without a
# reconfigure — and CMake only re-runs configure when a CMakeLists.txt changes,
# not when a header does. The id would then say "compatible" about an engine
# whose layout had moved, which is the exact failure this ticket exists to catch,
# reintroduced by the mechanism meant to catch it. T0123 hit the same class of
# bug from the other side; making the generator a real node in the build graph
# is the fix in both cases.
#
# Inputs (-D on the command line):
#   HP_ID_INCLUDE_DIR  public header root to hash
#   HP_ID_TARGET       target triple, e.g. x86_64-linux-gnu.2.28
#   HP_ID_CONFIG       CMAKE_BUILD_TYPE
#   HP_ID_PROFILING    ON/OFF
#   HP_ID_OUTPUT       header to write

# --- what goes into the id ---------------------------------------------------
#
# The question the id answers is "was this module compiled against this exact
# engine ABI", so every input is something that changes the answer:
#
#   * the public headers, because they are the layout
#   * the target triple, because a Windows module in a Linux process is not a
#     near-miss worth diagnosing separately
#   * the build type, because a Debug engine and a Release module differ in ways
#     no header hash can see (assertions, inlining, iterator debugging)
#   * HP_PROFILING, because it changes the engine's exported symbol surface and
#     the layout of anything embedding a zone object — and it is a switch a
#     developer flips casually without rebuilding everything
#
# The rule, which matters more than the list: **any flag that changes the
# engine's symbol surface or type layout belongs here.** Profiling is the first
# such flag; it will not be the last. Add them, and record why, rather than
# treating this list as complete.

file(GLOB _hp_headers "${HP_ID_INCLUDE_DIR}/hp/*.hpp")
list(SORT _hp_headers)   # glob order is filesystem order; the id must not be

if(NOT _hp_headers)
    message(FATAL_ERROR "hp_build_id: no headers under ${HP_ID_INCLUDE_DIR}/hp -- "
                        "refusing to mint an id that would claim compatibility with nothing")
endif()

# Hash file *contents*, not paths or timestamps, so a touched-but-unchanged
# header does not invalidate every module in the tree.
set(_hp_material "")
foreach(_h IN LISTS _hp_headers)
    file(SHA256 "${_h}" _h_hash)
    get_filename_component(_h_name "${_h}" NAME)
    string(APPEND _hp_material "${_h_name}:${_h_hash}\n")
endforeach()

string(APPEND _hp_material "target:${HP_ID_TARGET}\n")
string(APPEND _hp_material "config:${HP_ID_CONFIG}\n")
string(APPEND _hp_material "profiling:${HP_ID_PROFILING}\n")

string(SHA256 _hp_id "${_hp_material}")
string(SUBSTRING "${_hp_id}" 0 16 _hp_id_short)

# Written through a temporary and compared, so an unchanged id does not touch
# the file and trigger a rebuild of everything that includes it on every build.
set(_hp_content
"// Generated by cmake/hp_build_id.cmake (T0104). Do not edit, do not commit.
#pragma once
#define HP_BUILD_ID \"${_hp_id_short}\"
#define HP_BUILD_ID_TARGET \"${HP_ID_TARGET}\"
#define HP_BUILD_ID_CONFIG \"${HP_ID_CONFIG}\"
#define HP_BUILD_ID_PROFILING \"${HP_ID_PROFILING}\"
")

if(EXISTS "${HP_ID_OUTPUT}")
    file(READ "${HP_ID_OUTPUT}" _hp_existing)
    if(_hp_existing STREQUAL _hp_content)
        return()
    endif()
endif()

file(WRITE "${HP_ID_OUTPUT}" "${_hp_content}")
message(STATUS "hp: build id ${_hp_id_short} (${HP_ID_TARGET}, ${HP_ID_CONFIG}, profiling=${HP_ID_PROFILING})")
