# Embeds the engine's own shader sources into a generated C++ header (T0141).
#
# **Shaders are compiled into the binary, not read from disk**, which is the same
# thing DiligentFX does with its own (`shaders_list.h`, generated by their
# `convert_shaders_to_headers`). Three reasons it is worth copying rather than
# reading files at runtime:
#
# - **D13.** Every content read goes through the VFS. Engine shaders are not
#   content — they ship with the engine, not with a project — so the honest
#   answer is that they are not read at all.
# - **`dist` has nothing extra to install.** A shader directory beside the
#   executable is one more thing to get wrong, and the failure is a black screen
#   with no message.
# - A missing shader becomes a **link error**, not a runtime one.
#
# **Diligent's own generator is not reused, deliberately.** It shells out to a
# Python `file2string` script and calls `find_package(Python3 REQUIRED)`. The
# engine build does not currently need Python — only `zig build docs` does — and
# making the core build depend on it is a new requirement for every machine and
# for the offline-configure CI job. CMake can do the same work with no escaping
# at all by using a **raw string literal**, so it does.
#
# Invoked as a script:
#   cmake -DHP_SHADER_DIR=<dir> -DHP_SHADER_OUTPUT=<header> [-DHP_SHADER_EXTRA_FILES=<a;b>]
#         -P hp_embed_shaders.cmake
#
# HP_SHADER_EXTRA_FILES is a list of absolute paths embedded alongside the
# directory's own shaders, under their bare file names. It exists for
# `HLSLDefinitions.fxh` (T0142): Diligent *prepends* that file to HLSL sources
# itself, but slang resolves it as an ordinary `#include`, so the engine's
# factory has to be able to serve it. Read from the pinned submodule at build
# time -- the same bytes, regenerated whenever the submodule moves, so the copy
# cannot drift.

if(NOT DEFINED HP_SHADER_DIR OR NOT DEFINED HP_SHADER_OUTPUT)
    message(FATAL_ERROR "hp_embed_shaders.cmake needs HP_SHADER_DIR and HP_SHADER_OUTPUT")
endif()

file(GLOB _shader_files
     "${HP_SHADER_DIR}/*.vsh"
     "${HP_SHADER_DIR}/*.psh"
     "${HP_SHADER_DIR}/*.fxh"
     "${HP_SHADER_DIR}/*.slang")
list(SORT _shader_files)
if(DEFINED HP_SHADER_EXTRA_FILES)
    foreach(_extra IN LISTS HP_SHADER_EXTRA_FILES)
        if(NOT EXISTS "${_extra}")
            message(FATAL_ERROR "hp_embed_shaders.cmake: extra file '${_extra}' does not exist")
        endif()
        list(APPEND _shader_files "${_extra}")
    endforeach()
endif()

# **The delimiter is what makes escaping unnecessary, and it has to be one no
# shader contains.** `HPSHADER` is checked against every file below rather than
# assumed: a shader containing the closing sequence would silently truncate its
# own source, and the result would be a compile error inside generated code that
# nobody would think to look at.
set(_delim "HPSHADER")

set(_body "// Generated by cmake/hp_embed_shaders.cmake. Do not edit.\n")
string(APPEND _body "//\n")
string(APPEND _body "// One entry per shader source in engine/shaders/, embedded verbatim.\n")
string(APPEND _body "// Regenerated whenever a shader changes, because the sources are\n")
string(APPEND _body "// declared as dependencies of the custom command that runs this.\n\n")
string(APPEND _body "// clang-format off\n")
string(APPEND _body "static const Diligent::MemoryShaderSourceFileInfo g_hpShaders[] =\n{\n")

set(_count 0)
foreach(_file ${_shader_files})
    get_filename_component(_name "${_file}" NAME)
    file(READ "${_file}" _text)

    if(_text MATCHES "\\)${_delim}\"")
        message(FATAL_ERROR
                "shader '${_name}' contains the raw-string delimiter )${_delim}\", which would "
                "truncate it silently. Rename the delimiter in hp_embed_shaders.cmake.")
    endif()

    string(APPEND _body "    {\n        \"${_name}\",\n        R\"${_delim}(\n")
    string(APPEND _body "${_text}")
    string(APPEND _body ")${_delim}\"\n    },\n")
    math(EXPR _count "${_count} + 1")
endforeach()

string(APPEND _body "};\n")
string(APPEND _body "// clang-format on\n")
string(APPEND _body "\nstatic constexpr int g_hpShaderCount = ${_count};\n")

if(_count EQUAL 0)
    # Not a warning to scroll past: an empty list compiles, links, and produces a
    # renderer that cannot create a single pipeline state, which looks like a
    # device fault rather than a build one.
    message(FATAL_ERROR "no shaders found in '${HP_SHADER_DIR}'; the engine cannot render without them")
endif()

# `configure_file`-style write that leaves the timestamp alone when nothing
# changed, so touching one shader does not rebuild every consumer of the header.
if(EXISTS "${HP_SHADER_OUTPUT}")
    file(READ "${HP_SHADER_OUTPUT}" _existing)
    if(_existing STREQUAL _body)
        return()
    endif()
endif()
file(WRITE "${HP_SHADER_OUTPUT}" "${_body}")
message(STATUS "embedded ${_count} engine shader(s) into ${HP_SHADER_OUTPUT}")
