# Embeds one binary file into a generated C++ header as a byte array (T0143).
#
# The first user is the sheen albedo-scaling LUT: DiligentFX's `EnableSheen`
# needs `g_SheenAlbedoScalingLUT` bound, upstream ships the data only as a
# GLTFViewer *sample asset* (`sheen_albedo_scaling.jpg`) loaded from a native
# file path — and this engine has no native-path content reads (D13) and no
# interest in a file beside the executable whose absence is a black sheen
# term with no message. So the bytes are read from the pinned submodule at
# build time and compiled in, exactly as `hp_embed_shaders.cmake` does for
# `HLSLDefinitions.fxh`: same bytes, regenerated when the submodule moves, so
# the copy cannot drift.
#
# Kept separate from hp_embed_shaders.cmake because that script's contract is
# text (raw string literals, UTF-8, the `.slang`-only refusal); binary data
# needs hex encoding and none of the refusal rules. Two small scripts with one
# job each beat one with a mode switch.
#
# Invoked as a script:
#   cmake -DHP_BINARY_INPUT=<file> -DHP_BINARY_OUTPUT=<header>
#         -DHP_BINARY_SYMBOL=<identifier> -P hp_embed_binary.cmake

if(NOT HP_BINARY_INPUT OR NOT HP_BINARY_OUTPUT OR NOT HP_BINARY_SYMBOL)
    message(FATAL_ERROR "hp_embed_binary.cmake needs HP_BINARY_INPUT, HP_BINARY_OUTPUT and HP_BINARY_SYMBOL")
endif()

if(NOT EXISTS "${HP_BINARY_INPUT}")
    message(FATAL_ERROR "hp_embed_binary.cmake: input does not exist: ${HP_BINARY_INPUT} (is the submodule checked out?)")
endif()

file(READ "${HP_BINARY_INPUT}" _hex HEX)
string(LENGTH "${_hex}" _hexlen)
math(EXPR _size "${_hexlen} / 2")
if(_size EQUAL 0)
    message(FATAL_ERROR "hp_embed_binary.cmake: input is empty: ${HP_BINARY_INPUT}")
endif()

# 0xAB,0xCD,... with a line break every 20 bytes so the header stays diffable.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){20})" "\\1\n    " _bytes "${_bytes}")

get_filename_component(_source_name "${HP_BINARY_INPUT}" NAME)
file(WRITE "${HP_BINARY_OUTPUT}" "// Generated by cmake/hp_embed_binary.cmake from ${_source_name} -- do not edit.
#pragma once

namespace hp::embedded {

/// ${_source_name}, ${_size} bytes, byte for byte.
inline constexpr unsigned char ${HP_BINARY_SYMBOL}[] = {
    ${_bytes}
};

inline constexpr unsigned long ${HP_BINARY_SYMBOL}Size = ${_size}UL;

} // namespace hp::embedded
")
